### ISSUE TITLE
CloudFilesProvider.GetObjectMetaData returns an empty Dictionary

### ISSUE THREAD

**Issue by harshanandmv** [openstacknetsdk/openstack.net#633]
CloudFilesProvider.GetObjectMetaData returns an empty Dictionary all the time.
Even though swift provides detail like Content-Length	and Etag, the openstacknetsdk is filtering out all those headers and passing an empty dictionary. Would it be possible to pass back all the header values? 

http://developer.openstack.org/api-ref/object-storage/index.html?expanded=show-object-metadata-detail

On a quick look, CloudFilesMetadataProcessor.ProcessMetaData() seems to filtering them. Can this be enhanced to provide the details returned by Swift?

**Comment by carolynvs** [comment]
The information you are looking for, such as Etag, are headers, not metadata on the object, which the SDK treats differently*. Here's an example of how to collect all the information (both metadata and headers) for an object:

```csharp
using System;
using System.Collections.Generic;
using net.openstack.Core.Domain;
using net.openstack.Providers.Rackspace;

namespace GetMiscObjectHeaders
{
    class Program
    {
        static void Main(string[] args)
        {
            const string region = "DFW";
            var user = new CloudIdentity
            {
                Username = "username",
                APIKey = "apikey"
            };

            var cloudFiles = new CloudFilesProvider(user);

            string container = "test";
            string file = "test.gif";

            Console.WriteLine("Inspecting {0}/{1}...", container, file);

            Console.WriteLine("Metadata:");
            var metadatas = cloudFiles.GetObjectMetaData(container, file, region);
            foreach (KeyValuePair<string, string> metadata in metadatas)
            {
                Console.WriteLine("  {0}: {1}", metadata.Key, metadata.Value);
            }

            Console.WriteLine("Headers:");
            var headers = cloudFiles.GetObjectHeaders(container, file, region);
            foreach (KeyValuePair<string, string> header in headers)
            {
                Console.WriteLine("  {0}: {1}", header.Key, header.Value);
            }

            Console.ReadLine();
        }
    }
}

```

```
Inspecting test/test.gif...
Metadata:
  Foobar: stuff
Headers:
  X-Timestamp: 1476726593.38178
  X-Trans-Id: txe6877d1665c9459faf317-0058050f70dfw1
  Accept-Ranges: bytes
  Content-Length: 663595
  Content-Type: image/gif
  Date: Mon, 17 Oct 2016 17:50:40 GMT
  ETag: 1e8f9e1ad3164c30f16373531a30f0b0
  Last-Modified: Mon, 17 Oct 2016 17:49:54 GMT
```

\* I am not sure why the SDK treats them differently, it's the same API call and this forces a duplicate call to collect all the info... At this point, altering this behavior this would be a breaking change, and would need to go into v2. Hopefully the workaround is enough for now.
